packages:
  - examples/*
  - docs
allowBuilds:
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  core-js-pure: set this to true or false
  esbuild: set this to true or false
  fsevents: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
  nice-napi: set this to true or false
